import 'package:flutter/material.dart';
import 'package:heroicons/heroicons.dart';
import 'package:trakli/domain/entities/category_entity.dart';
import 'package:trakli/gen/translations/codegen_loader.g.dart';
import 'package:trakli/presentation/utils/enums.dart';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();
final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
    GlobalKey<ScaffoldMessengerState>();

void resetScaffoldKey() {
  scaffoldKey = GlobalKey<ScaffoldState>();
}

const String maxUploadSizeInMB = "5Mo";
final List<Locale> supportedLanguages = [
  const Locale('en'),
  const Locale('fr'),
  const Locale('de'),
  const Locale('es'),
  const Locale('it'),
  const Locale('ru'),
];

final List<String> supportedFormDisplays = [
  'full',
  'compact',
];

List<CategoryEntity> incomeTransactions = [
  CategoryEntity(
    name: "Salary",
    type: TransactionType.income,
    clientId: "1",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Freelance",
    type: TransactionType.income,
    clientId: "2",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Investments",
    type: TransactionType.income,
    clientId: "3",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Gifts",
    type: TransactionType.income,
    clientId: "4",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Refunds",
    type: TransactionType.income,
    clientId: "5",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Other Income",
    type: TransactionType.income,
    clientId: "6",
    createdAt: DateTime.now(),
  ),
];

List<CategoryEntity> expenseTransactions = [
  CategoryEntity(
    name: "Food & Dining",
    type: TransactionType.expense,
    clientId: "7",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Transportation",
    type: TransactionType.expense,
    clientId: "8",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Housing",
    type: TransactionType.expense,
    clientId: "9",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Utilities",
    type: TransactionType.expense,
    clientId: "10",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Healthcare",
    type: TransactionType.expense,
    clientId: "11",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Entertainment",
    type: TransactionType.expense,
    clientId: "12",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Shopping",
    type: TransactionType.expense,
    clientId: "13",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Personal Care",
    type: TransactionType.expense,
    clientId: "14",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Education",
    type: TransactionType.expense,
    clientId: "15",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Subscriptions",
    type: TransactionType.expense,
    clientId: "16",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Insurance",
    type: TransactionType.expense,
    clientId: "17",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Savings",
    type: TransactionType.expense,
    clientId: "18",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Gifts & Donations",
    type: TransactionType.expense,
    clientId: "19",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Travel",
    type: TransactionType.expense,
    clientId: "20",
    createdAt: DateTime.now(),
  ),
  CategoryEntity(
    name: "Other Expenses",
    type: TransactionType.expense,
    clientId: "21",
    createdAt: DateTime.now(),
  ),
];

final List<IconData> availableIcons = [
  Icons.home,
  Icons.shopping_cart,
  Icons.electrical_services,
  Icons.directions_bus,
  Icons.local_hospital,
  Icons.fitness_center,
  Icons.shopping_bag,
  Icons.flight,
  Icons.payments,
  Icons.work,
  Icons.card_giftcard,
  Icons.volunteer_activism,
  Icons.attach_money,
  Icons.fastfood,
  Icons.restaurant,
  Icons.sports_soccer,
  Icons.school,
  Icons.movie,
  Icons.pets,
  Icons.local_gas_station,
  Icons.phone,
  Icons.laptop,
  Icons.music_note,
  Icons.spa,
  Icons.park,
  Icons.coffee,
  Icons.directions_car,
  Icons.train,
  Icons.beach_access,
  Icons.local_mall,
  Icons.local_cafe,
  Icons.local_pizza,
  Icons.local_bar,
  Icons.health_and_safety,
  Icons.child_care,
  Icons.directions_walk,
  Icons.trending_up,
  Icons.trending_down,
  Icons.savings,
  Icons.sports_basketball,
  Icons.event,
  Icons.local_florist,
  Icons.kitchen,
  Icons.wine_bar,
  Icons.videogame_asset,
  Icons.watch,
  Icons.airplane_ticket,
  Icons.car_repair,
  Icons.directions_bike,
  Icons.cake,
  Icons.sanitizer,
];

final List<HeroIcons> heroIconsCategories = [
  HeroIcons.academicCap,
  HeroIcons.arrowTrendingDown,
  HeroIcons.arrowTrendingUp,
  HeroIcons.banknotes,
  HeroIcons.battery100,
  HeroIcons.bellAlert,
  HeroIcons.bolt,
  HeroIcons.bookOpen,
  HeroIcons.briefcase,
  HeroIcons.buildingLibrary,
  HeroIcons.buildingOffice,
  HeroIcons.buildingOffice2,
  HeroIcons.cake,
  HeroIcons.calculator,
  HeroIcons.calendarDays,
  HeroIcons.camera,
  HeroIcons.chartBar,
  HeroIcons.clock,
  HeroIcons.cog6Tooth,
  HeroIcons.computerDesktop,
  HeroIcons.creditCard,
  HeroIcons.currencyDollar,
  HeroIcons.devicePhoneMobile,
  HeroIcons.envelope,
  HeroIcons.envelopeOpen,
  HeroIcons.exclamationCircle,
  HeroIcons.exclamationTriangle,
  HeroIcons.eye,
  HeroIcons.eyeDropper,
  HeroIcons.film,
  HeroIcons.folder,
  HeroIcons.gift,
  HeroIcons.globeAlt,
  HeroIcons.heart,
  HeroIcons.home,
  HeroIcons.homeModern,
  HeroIcons.identification,
  HeroIcons.hashtag,
  HeroIcons.lifebuoy,
  HeroIcons.lightBulb,
  HeroIcons.inboxArrowDown,
  HeroIcons.mapPin,
  HeroIcons.megaphone,
  HeroIcons.microphone,
  HeroIcons.moon,
  HeroIcons.musicalNote,
  HeroIcons.pencilSquare,
  HeroIcons.phoneXMark,
  HeroIcons.presentationChartLine,
  HeroIcons.photo,
  HeroIcons.phone,
  HeroIcons.phoneArrowUpRight,
  HeroIcons.printer,
  HeroIcons.questionMarkCircle,
  HeroIcons.radio,
  HeroIcons.receiptPercent,
  HeroIcons.receiptRefund,
  HeroIcons.rectangleStack,
  HeroIcons.rocketLaunch,
  HeroIcons.rss,
  HeroIcons.scissors,
  HeroIcons.shoppingBag,
  HeroIcons.shoppingCart,
  HeroIcons.signal,
  HeroIcons.share,
  HeroIcons.star,
  HeroIcons.sparkles,
  HeroIcons.speakerWave,
  HeroIcons.tag,
  HeroIcons.ticket,
  HeroIcons.trash,
  HeroIcons.trophy,
  HeroIcons.truck,
  HeroIcons.tv,
  HeroIcons.user,
  HeroIcons.users,
  HeroIcons.videoCamera,
  HeroIcons.wifi,
  HeroIcons.wrench,
  HeroIcons.wrenchScrewdriver,
];

const String loremIpsum =
    "Lorem ipsum dolor sit amet consectetur. Aliquam integer at sed a at leo vulputate at. Etiam blandit proin amet.";

List<String> dateOptions = [
  LocaleKeys.thisWeek,
  LocaleKeys.thisMonth,
  LocaleKeys.lastThreeMonths,
  LocaleKeys.lastSixMonths,
  LocaleKeys.thisYear,
  LocaleKeys.custom,
];
