import 'package:flutter/material.dart';
import 'package:heroicons/heroicons.dart';
import 'package:trakli/data/database/tables/enums.dart';
import 'package:trakli/domain/entities/category_entity.dart';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();
final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
    GlobalKey<ScaffoldMessengerState>();
const String maxUploadSizeInMB = "5Mo";
final List<Locale> supportedLanguages = [
  const Locale('en'),
  const Locale('fr'),
  const Locale('de'),
  const Locale('es'),
  const Locale('it'),
];

final List<String> supportedFormDisplays = [
  'full',
  'compact',
];

List<CategoryEntity> incomeTransactions = const [
  CategoryEntity(
    name: "Salary",
    type: CategoryType.income,
    clientGeneratedId: "1",
  ),
  CategoryEntity(
    name: "Freelance",
    type: CategoryType.income,
    clientGeneratedId: "2",
  ),
  CategoryEntity(
    name: "Gifts",
    type: CategoryType.income,
    clientGeneratedId: "3",
  ),
  CategoryEntity(
    name: "Donations",
    type: CategoryType.income,
    clientGeneratedId: "4",
  ),
  CategoryEntity(
    name: "Other Income",
    type: CategoryType.income,
    clientGeneratedId: "5",
  ),
];

List<CategoryEntity> expenseTransactions = const [
  CategoryEntity(
    name: "Rent",
    type: CategoryType.expense,
    clientGeneratedId: "6",
  ),
  CategoryEntity(
    name: "Groceries",
    type: CategoryType.expense,
    clientGeneratedId: "7",
  ),
  CategoryEntity(
    name: "Utilities",
    type: CategoryType.expense,
    clientGeneratedId: "8",
  ),
  CategoryEntity(
    name: "Transportation",
    type: CategoryType.expense,
    clientGeneratedId: "9",
  ),
  CategoryEntity(
    name: "Health",
    type: CategoryType.expense,
    clientGeneratedId: "10",
  ),
  CategoryEntity(
    name: "Fitness",
    type: CategoryType.expense,
    clientGeneratedId: "11",
  ),
  CategoryEntity(
    name: "Shopping",
    type: CategoryType.expense,
    clientGeneratedId: "12",
  ),
  CategoryEntity(
    name: "Travel",
    type: CategoryType.expense,
    clientGeneratedId: "13",
  ),
];

final List<IconData> availableIcons = [
  Icons.home,
  Icons.shopping_cart,
  Icons.electrical_services,
  Icons.directions_bus,
  Icons.local_hospital,
  Icons.fitness_center,
  Icons.shopping_bag,
  Icons.flight,
  Icons.payments,
  Icons.work,
  Icons.card_giftcard,
  Icons.volunteer_activism,
  Icons.attach_money,
  Icons.fastfood,
  Icons.restaurant,
  Icons.sports_soccer,
  Icons.school,
  Icons.movie,
  Icons.pets,
  Icons.local_gas_station,
  Icons.phone,
  Icons.laptop,
  Icons.music_note,
  Icons.spa,
  Icons.park,
  Icons.coffee,
  Icons.directions_car,
  Icons.train,
  Icons.beach_access,
  Icons.local_mall,
  Icons.local_cafe,
  Icons.local_pizza,
  Icons.local_bar,
  Icons.health_and_safety,
  Icons.child_care,
  Icons.directions_walk,
  Icons.trending_up,
  Icons.trending_down,
  Icons.savings,
  Icons.sports_basketball,
  Icons.event,
  Icons.local_florist,
  Icons.kitchen,
  Icons.wine_bar,
  Icons.videogame_asset,
  Icons.watch,
  Icons.airplane_ticket,
  Icons.car_repair,
  Icons.directions_bike,
  Icons.cake,
  Icons.sanitizer,
];

final List<HeroIcons> heroIconsCategories = [
  HeroIcons.academicCap,
  HeroIcons.arrowTrendingDown,
  HeroIcons.arrowTrendingUp,
  HeroIcons.banknotes,
  HeroIcons.battery100,
  HeroIcons.bellAlert,
  HeroIcons.bolt,
  HeroIcons.bookOpen,
  HeroIcons.briefcase,
  HeroIcons.buildingLibrary,
  HeroIcons.buildingOffice,
  HeroIcons.buildingOffice2,
  HeroIcons.cake,
  HeroIcons.calculator,
  HeroIcons.calendarDays,
  HeroIcons.camera,
  HeroIcons.chartBar,
  HeroIcons.clock,
  HeroIcons.cog6Tooth,
  HeroIcons.computerDesktop,
  HeroIcons.creditCard,
  HeroIcons.currencyDollar,
  HeroIcons.devicePhoneMobile,
  HeroIcons.envelope,
  HeroIcons.envelopeOpen,
  HeroIcons.exclamationCircle,
  HeroIcons.exclamationTriangle,
  HeroIcons.eye,
  HeroIcons.eyeDropper,
  HeroIcons.film,
  HeroIcons.folder,
  HeroIcons.gift,
  HeroIcons.globeAlt,
  HeroIcons.heart,
  HeroIcons.home,
  HeroIcons.homeModern,
  HeroIcons.identification,
  HeroIcons.hashtag,
  HeroIcons.lifebuoy,
  HeroIcons.lightBulb,
  HeroIcons.inboxArrowDown,
  HeroIcons.mapPin,
  HeroIcons.megaphone,
  HeroIcons.microphone,
  HeroIcons.moon,
  HeroIcons.musicalNote,
  HeroIcons.pencilSquare,
  HeroIcons.phoneXMark,
  HeroIcons.presentationChartLine,
  HeroIcons.photo,
  HeroIcons.phone,
  HeroIcons.phoneArrowUpRight,
  HeroIcons.printer,
  HeroIcons.questionMarkCircle,
  HeroIcons.radio,
  HeroIcons.receiptPercent,
  HeroIcons.receiptRefund,
  HeroIcons.rectangleStack,
  HeroIcons.rocketLaunch,
  HeroIcons.rss,
  HeroIcons.scissors,
  HeroIcons.shoppingBag,
  HeroIcons.shoppingCart,
  HeroIcons.signal,
  HeroIcons.share,
  HeroIcons.star,
  HeroIcons.sparkles,
  HeroIcons.speakerWave,
  HeroIcons.tag,
  HeroIcons.ticket,
  HeroIcons.trash,
  HeroIcons.trophy,
  HeroIcons.truck,
  HeroIcons.tv,
  HeroIcons.user,
  HeroIcons.users,
  HeroIcons.videoCamera,
  HeroIcons.wifi,
  HeroIcons.wrench,
  HeroIcons.wrenchScrewdriver,
];
